apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.26.1 (1b040dd2)
  creationTimestamp: null
  labels:
    io.kompose.service: postgres-citizenlab
  name: postgres-citizenlab
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: postgres-citizenlab
  strategy:
    type: Recreate
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert
        kompose.version: 1.26.1 (1b040dd2)
      creationTimestamp: null
      labels:
        io.kompose.service: postgres-citizenlab
    spec:
      containers:
        - env:
            - name: POSTGRES_PASSWORD
              value: postgres
            - name: POSTGRES_USER
              value: postgres
          image: postgis/postgis:12-3.1
          readinessProbe:
            exec:
              command:
                - /usr/bin/psql
                - -U
                - postgres
                - -d
                - postgres
                - -c
                - SELECT 1
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 30
          livenessProbe:
            exec:
              command:
                - /usr/bin/psql
                - -U
                - postgres
                - -d
                - postgres
                - -c
                - SELECT 1
            failureThreshold: 3
            periodSeconds: 30
            timeoutSeconds: 30
          name: postgres-citizenlab
          ports:
            - containerPort: 5432
          resources: {}
          volumeMounts:
            - mountPath: /var/lib/postgresql/data
              name: postgres-citizenlab
      restartPolicy: Always
      volumes:
        - name: postgres-citizenlab
          persistentVolumeClaim:
            claimName: postgres-citizenlab
status: {}
